/**
 * BoardScope Fault Tree Module
 * Manufacturer-specific diagnostic trees for Nintendo, HP, MacBook, and more.
 * Each manufacturer has unique power rails, signal names, and common failure points.
 */

// ═══════════════════════════════════════════════════════════
// MANUFACTURER-SPECIFIC FAULT TREES
// ═══════════════════════════════════════════════════════════

const FAULT_TREES = {
  // ── APPLE MACBOOK ──────────────────────────────────────
  macbook: {
    name: 'Apple MacBook',
    icon: '🍎',
    boards: ['A2179', 'A2289', 'A2251', 'A2141', 'A1990', 'A1989', 'A1706', 'A1707', 'A1502', 'A1466', 'A1465', 'A1398', 'A1369'],
    symptoms: [
      {
        symptom: 'No Power / Dead Board',
        steps: [
          { text: 'Check battery connector voltage (VBAT)', nets: ['PPBAT_BAT'], hint: 'Should be 7.2–8.7V on Li-Ion MacBook boards' },
          { text: 'Probe PPBUS_G3H (main system bus)', nets: ['PPBUS_G3H'], hint: 'Primary input to PMIC, ~8.4V on Apple boards. Generated by ISL9239/CD3215' },
          { text: 'Check CD3215/CD3217 charger IC', nets: ['PPVDI'], hint: 'Apple USB-C charger IC. Check VBUS input on pins 1-4' },
          { text: 'Verify PP3V42_G3H (always-on rail)', nets: ['PP3V42_G3H'], hint: 'Always-on 3.42V from PPBUS via LDO. Present even when board is off' },
          { text: 'Check SMC power sequencing', nets: ['PM_SLP_S5_L', 'PM_SLP_S3_L', 'PM_SLP_S0_L'], hint: 'SLP_S5 must deassert before S3, then S0. SMC controls power state' },
          { text: 'Probe PP5V_S5 / PP5V_S0', nets: ['PP5V_S5', 'PP5V_S0'], hint: '5V rails from PMIC. S5 is always-on, S0 is active state' },
          { text: 'Check PP3V3_S5 / PP3V3_S0', nets: ['PP3V3_S5', 'PP3V3_S0'], hint: '3.3V rails. S5 always-on, S0 when system is running' },
          { text: 'Verify T2/SMC communication', nets: ['I2C_SMC', 'SMB_SMC'], hint: 'T2 chip (2018+) or SMC handles power management' },
        ]
      },
      {
        symptom: 'No Charging / USB-C Not Recognized',
        steps: [
          { text: 'Verify VBUS on USB-C port', nets: ['VBUS', 'VBUS_FS'], hint: '5–20V from charger adapter. Check both CC pins for negotiation' },
          { text: 'Check CD3215/CD3217 ACOK signal', nets: ['ACOK', 'CHGR_ACOK'], hint: 'Should go high when charger connected and CC negotiation complete' },
          { text: 'Probe charge FET (GATE_CHG)', nets: ['GATE_CHG', 'CHGR_FET'], hint: 'FET must be open for charge current to flow to PPBUS' },
          { text: 'Check PPBUS voltage with charger', nets: ['PPBUS_G3H'], hint: 'Should be slightly above battery voltage when charging' },
          { text: 'Verify SMBus to charger IC', nets: ['SMB_CLK', 'SMB_DAT'], hint: 'Charger IC communicates with SMC via SMBus' },
          { text: 'Check USB-C port CC lines', nets: ['CC1', 'CC2'], hint: 'CC pins negotiate PD contract. Should show 0.5-1.2V' },
        ]
      },
      {
        symptom: 'No Backlight',
        steps: [
          { text: 'Check PPVOUT_SW_BL (backlight boost)', nets: ['PPVOUT_SW_BL', 'LCD_BKL_PWR'], hint: 'Should be 20–40V boosted from PPBUS via LP8556/RT4831' },
          { text: 'Verify BKL_PWM from GPU/PCH', nets: ['BKL_PWM', 'LCD_BKL_PWM'], hint: 'PWM duty cycle controls brightness. Check with oscilloscope' },
          { text: 'Probe BKL_EN enable line', nets: ['BKL_EN', 'LCD_BKL_EN'], hint: 'Must be high for boost to run. From PCH or GPU' },
          { text: 'Check boost IC coil continuity', nets: [], hint: 'Shorted coil = zero output voltage. Common on LP8556' },
          { text: 'Inspect LCD connector pins', nets: [], hint: 'Especially BKL+ and BKL- pins. Look for bent/dirty contacts' },
        ]
      },
      {
        symptom: 'No Display / Black Screen',
        steps: [
          { text: 'Check PPVCORE_GPU', nets: ['PPVCORE_GPU', 'GPU_CORE'], hint: 'Missing GPU core voltage = black screen with power' },
          { text: 'Check eDP connector', nets: [], hint: 'Cold joint or debris on LCD flex connector. Check pin 1-40' },
          { text: 'Probe PP3V3_MLDO', nets: ['PP3V3_MLDO', 'LCD_VCC'], hint: '3.3V panel supply from GPU power block' },
          { text: 'Verify VDDIO_LCD', nets: ['VDDIO_LCD'], hint: '1.8V or 1.2V I/O supply for panel controller' },
          { text: 'Check GPU clock activity', nets: [], hint: 'Any clock activity suggests GPU is alive. Probe with scope' },
          { text: 'Verify T2/Display bridge', nets: ['I2C_DISP'], hint: 'T2 chip (2018+) handles display initialization' },
        ]
      },
      {
        symptom: 'No Audio',
        steps: [
          { text: 'Check AVDD to audio codec', nets: ['AVDD', 'PVDD', 'PP3V3_AUDIO'], hint: 'Audio codec analog supply. Usually 3.3V' },
          { text: 'Probe I2S/MCLK lines', nets: ['I2S_CLK', 'MCLK', 'AUD_MCLK'], hint: 'No clock = no audio output. From PCH/SoC' },
          { text: 'Verify speaker amp supply', nets: ['PVDD_SPK'], hint: 'Usually 5–12V boosted supply for amplifier' },
          { text: 'Check headphone detection', nets: ['HPDET', 'HP_DET'], hint: 'Detection pin selects speaker vs headphone output' },
        ]
      },
      {
        symptom: 'No USB / Thunderbolt',
        steps: [
          { text: 'Verify PP5V_USB on port', nets: ['VBUS', 'PP5V_USB'], hint: 'USB fuse often blows from ESD or short' },
          { text: 'Check Intel/ASM retimer power', nets: [], hint: 'Retimer needs 1.0V, 1.8V, 3.3V rails' },
          { text: 'Probe USB2 DP/DM', nets: ['USB2_DP', 'USB2_DM'], hint: 'Should show ~400mV termination voltage at idle' },
          { text: 'Verify Thunderbolt lanes', nets: ['USB3_TX', 'USB3_RX'], hint: 'Check for 50Ω continuity to retimer IC' },
          { text: 'Check SMC USB power enable', nets: ['PP5V_USB_EN', 'USBPWR_EN'], hint: 'SMC controls USB VBUS FET' },
        ]
      },
      {
        symptom: 'Keyboard/Trackpad Not Working',
        steps: [
          { text: 'Check PP3V3_S5 for keyboard controller', nets: ['PP3V3_S5'], hint: 'Keyboard controller needs always-on 3.3V' },
          { text: 'Verify I2C keyboard bus', nets: ['I2C_KBD', 'SMB_KBD'], hint: 'Keyboard communicates via I2C to SMC' },
          { text: 'Check trackpad I2C lines', nets: ['I2C_TP', 'SMB_TP'], hint: 'Trackpad uses I2C to PCH/SoC' },
          { text: 'Verify flex cable connection', nets: [], hint: 'Top case flex cable often damaged or loose' },
        ]
      },
      {
        symptom: 'WiFi/Bluetooth Not Working',
        steps: [
          { text: 'Check PP3V3_WLAN supply', nets: ['PP3V3_WLAN', 'PP3V3_WIFI'], hint: 'WiFi card needs 3.3V always-on rail' },
          { text: 'Verify PCIe WiFi bus', nets: ['PCIE_WIFI'], hint: 'WiFi connects via PCIe to PCH' },
          { text: 'Check antenna connections', nets: [], hint: 'Main/Aux antenna connectors often loose' },
          { text: 'Verify I2C WiFi control', nets: ['I2C_WIFI'], hint: 'WiFi enable via I2C from SMC' },
        ]
      },
    ]
  },

  // ── HP MOTHERBOARDS ────────────────────────────────────
  hp: {
    name: 'HP Laptop/Motherboard',
    icon: '💻',
    boards: ['845 G8', '850 G8', 'EliteBook 840', 'ProBook 450', 'Pavilion 15', 'ENVY 13', 'Spectre x360', 'OMEN 15', 'Victus 16'],
    symptoms: [
      {
        symptom: 'No Power / Dead Board',
        steps: [
          { text: 'Check main adapter input (DCIN)', nets: ['DCIN', 'VCC_IN'], hint: 'Should be 19V from HP adapter. Check adapter ID pin' },
          { text: 'Probe main 3V/5V ALW rails', nets: ['VCC_3V_ALW', 'VCC_5V_ALW', 'PP3V_ALW', 'PP5V_ALW'], hint: 'Always-on rails from primary PWM. Check TPS51125/RT8205' },
          { text: 'Check EC (Embedded Controller)', nets: ['EC_RST', 'EC_CLK'], hint: 'HP uses ITE/Nuvoton EC. Check 32.768kHz crystal' },
          { text: 'Verify PCH power', nets: ['VCC_PCH', 'PP1V05_PCH'], hint: 'PCH needs 1.05V standby rail' },
          { text: 'Check power button signal', nets: ['PWR_BTN', 'PWR_SW', 'EC_PWRBTN'], hint: 'Should pull low when pressed. From EC to PCH' },
          { text: 'Verify SLP_S5/S3/S0 signals', nets: ['SLP_S5', 'SLP_S3', 'SLP_S0'], hint: 'Power sequencing: S5→S3→S0' },
          { text: 'Check CPU VRM input', nets: ['VCC_CORE', 'VCORE'], hint: 'CPU core voltage from VRM controller' },
        ]
      },
      {
        symptom: 'No Charging',
        steps: [
          { text: 'Verify DCIN voltage', nets: ['DCIN', 'VCC_IN'], hint: '19V from HP adapter. Check center pin for adapter ID' },
          { text: 'Check charging IC (BQ24780S/etc)', nets: ['ACOK', 'ACPRB'], hint: 'ACOK should go high when adapter detected' },
          { text: 'Probe charge current sense', nets: ['CSP', 'CSN'], hint: 'Current sense pins on charging IC' },
          { text: 'Check battery communication', nets: ['SMB_CLK', 'SMB_DAT', 'SMB_ALERT'], hint: 'SMBus to battery for smart charging' },
          { text: 'Verify charge FET', nets: ['GATE_DRV'], hint: 'Charge FET gate drive from charging IC' },
        ]
      },
      {
        symptom: 'No Display',
        steps: [
          { text: 'Check GPU core voltage', nets: ['VCC_GPU', 'GPU_CORE'], hint: 'Missing GPU voltage = no display' },
          { text: 'Verify eDP panel power', nets: ['VDD', 'VDD_PANEL'], hint: '3.3V panel supply from PCH/GPU' },
          { text: 'Check eDP backlight enable', nets: ['BKL_EN', 'BL_EN'], hint: 'Backlight enable from GPU' },
          { text: 'Probe eDP data lines', nets: ['EDP_TX', 'EDP_RX'], hint: 'eDP differential pairs to panel' },
          { text: 'Check RAM voltage', nets: ['VDDQ', 'VPP'], hint: 'Unstable RAM voltage causes no POST' },
        ]
      },
      {
        symptom: 'No Backlight',
        steps: [
          { text: 'Check backlight boost IC', nets: ['BKL_VOUT', 'BL_VOUT'], hint: 'Should be 20-40V from boost converter' },
          { text: 'Verify BKL_PWM signal', nets: ['BKL_PWM', 'BL_PWM'], hint: 'PWM from GPU controls brightness' },
          { text: 'Check BKL_EN', nets: ['BKL_EN', 'BL_EN'], hint: 'Enable signal must be high' },
          { text: 'Probe boost coil', nets: [], hint: 'Check for shorted coil in boost circuit' },
        ]
      },
      {
        symptom: 'No USB',
        steps: [
          { text: 'Check USB 5V rail', nets: ['VCC_5V_USB', 'PP5V_USB'], hint: '5V USB supply from 5V ALW' },
          { text: 'Verify USB controller power', nets: ['VCC_USB'], hint: 'USB controller needs 3.3V standby' },
          { text: 'Probe USB DP/DM', nets: ['USB_DP', 'USB_DM'], hint: 'Should show ~400mV at idle' },
          { text: 'Check USB overcurrent protection', nets: ['USB_OC'], hint: 'Overcurrent pin pulls low on short' },
        ]
      },
      {
        symptom: 'No WiFi',
        steps: [
          { text: 'Check 3.3V WiFi rail', nets: ['VCC_3V_WLAN', 'PP3V3_WIFI'], hint: 'WiFi card needs 3.3V' },
          { text: 'Verify PCIe WiFi bus', nets: ['PCIE_WIFI'], hint: 'WiFi connects via mini-PCIe or M.2' },
          { text: 'Check WiFi enable', nets: ['WIFI_EN', 'WIFI_DISABLE'], hint: 'WiFi enable from EC' },
          { text: 'Verify antenna connections', nets: [], hint: 'Main/Aux antenna connectors' },
        ]
      },
    ]
  },

  // ── NINTENDO SWITCH ────────────────────────────────────
  nintendo_switch: {
    name: 'Nintendo Switch',
    icon: '🎮',
    boards: ['HAC-001', 'HAC-001(-01)', 'HDH-001', 'HEG-001'],
    symptoms: [
      {
        symptom: 'No Power / Dead Console',
        steps: [
          { text: 'Check battery connector voltage', nets: ['VBAT', 'BATT_VCC'], hint: 'Should be 3.6-4.2V from Li-Ion battery' },
          { text: 'Probe main PMIC input', nets: ['VIN_PMIC', 'VCC_IN'], hint: 'Input to M92T36/Maxim PMIC' },
          { text: 'Check M92T36 charger IC', nets: ['M92T36', 'CHG_IC'], hint: 'Nintendo Switch uses M92T36 for charging' },
          { text: 'Verify 1.8V standby rail', nets: ['PP1V8_STBY', 'VCC_1V8'], hint: 'Always-on 1.8V for CPU standby' },
          { text: 'Check power button circuit', nets: ['PWR_BTN', 'POWER_KEY'], hint: 'Power button pulls line to ground' },
          { text: 'Verify CPU power rails', nets: ['VDD_CPU', 'VCC_CPU'], hint: 'Tegra X1 needs multiple voltage rails' },
          { text: 'Check eMMC power', nets: ['VCC_EMMC', 'VDD_EMMC'], hint: 'eMMC needs 3.3V and 1.8V for boot' },
        ]
      },
      {
        symptom: 'No Charging',
        steps: [
          { text: 'Verify USB-C VBUS input', nets: ['VBUS', 'VCC_5V'], hint: '5V from USB-C charger' },
          { text: 'Check M92T36 ACOK', nets: ['ACOK', 'CHG_STAT'], hint: 'Charge status indicator' },
          { text: 'Probe charge FET', nets: ['CHG_FET', 'GATE_CHG'], hint: 'Charge FET controls current to battery' },
          { text: 'Check USB-C CC lines', nets: ['CC1', 'CC2'], hint: 'CC pins for charger detection' },
          { text: 'Verify battery thermistor', nets: ['BATT_THM', 'NTC_BATT'], hint: 'Temperature sensor for safe charging' },
        ]
      },
      {
        symptom: 'No Display',
        steps: [
          { text: 'Check display power rail', nets: ['VDD_DISP', 'VCC_LCD'], hint: 'Display needs 3.3V and 1.8V' },
          { text: 'Verify eDP/MIPI lines', nets: ['MIPI_DSI', 'EDP_TX'], hint: 'Display data from Tegra X1' },
          { text: 'Check backlight boost', nets: ['BKL_VOUT', 'BL_VOUT'], hint: 'Backlight boost for LCD panel' },
          { text: 'Probe display reset', nets: ['LCD_RST', 'DISP_RST'], hint: 'Display reset from CPU' },
        ]
      },
      {
        symptom: 'Joy-Con Not Connecting',
        steps: [
          { text: 'Check Joy-Con rail power', nets: ['VCC_JC', 'PP3V3_JC'], hint: 'Joy-Con rails from main PMIC' },
          { text: 'Verify Bluetooth module', nets: ['BT_VCC', 'VCC_BT'], hint: 'Bluetooth for wireless Joy-Con' },
          { text: 'Check SL/SR connectors', nets: ['SL_CON', 'SR_CON'], hint: 'Slide rail connectors for detection' },
          { text: 'Probe I2C Joy-Con bus', nets: ['I2C_JC', 'JC_I2C'], hint: 'Joy-Con communicates via I2C' },
        ]
      },
      {
        symptom: 'No HDMI Output (Dock)',
        steps: [
          { text: 'Check dock USB-C power', nets: ['VCC_DOCK', 'PP5V_DOCK'], hint: 'Dock needs 5V from USB-C' },
          { text: 'Verify HDMI encoder', nets: ['VCC_HDMI', 'HDMI_VCC'], hint: 'HDMI encoder needs 3.3V and 1.8V' },
          { text: 'Check HDMI data lines', nets: ['HDMI_TX', 'HDMI_D+'], hint: 'HDMI differential pairs' },
          { text: 'Probe HDMI HPD', nets: ['HDMI_HPD', 'HPD'], hint: 'Hot Plug Detect from TV' },
        ]
      },
      {
        symptom: 'No Audio',
        steps: [
          { text: 'Check audio codec power', nets: ['VCC_AUDIO', 'PP3V3_AUD'], hint: 'Audio codec needs 3.3V' },
          { text: 'Verify I2S audio bus', nets: ['I2S_CLK', 'I2S_DOUT'], hint: 'Audio data from Tegra X1' },
          { text: 'Check speaker amplifier', nets: ['SPK_VCC', 'AMP_VCC'], hint: 'Speaker amp needs 5V' },
          { text: 'Probe headphone jack', nets: ['HP_DET', 'HP_OUT'], hint: 'Headphone detection and output' },
        ]
      },
    ]
  },

  // ── NINTENDO 3DS ───────────────────────────────────────
  nintendo_3ds: {
    name: 'Nintendo 3DS/2DS',
    icon: '🎮',
    boards: ['CTR-001', 'SPR-001', 'FTR-001', 'KTR-001'],
    symptoms: [
      {
        symptom: 'No Power',
        steps: [
          { text: 'Check battery voltage', nets: ['VBAT', 'BATT'], hint: 'Should be 3.7V from Li-Ion battery' },
          { text: 'Verify power IC input', nets: ['VIN', 'VCC_IN'], hint: 'Input to power management IC' },
          { text: 'Check power button', nets: ['PWR_BTN', 'POWER'], hint: 'Power button circuit' },
          { text: 'Probe 3.3V rail', nets: ['PP3V3', 'VCC_3V3'], hint: 'Main 3.3V rail for CPU' },
        ]
      },
      {
        symptom: 'No Display (Top Screen)',
        steps: [
          { text: 'Check LCD power', nets: ['VCC_LCD', 'LCD_VCC'], hint: 'Top LCD needs 3.3V' },
          { text: 'Verify flex cable', nets: [], hint: 'Top screen flex cable through hinge' },
          { text: 'Check backlight', nets: ['BKL_VCC'], hint: 'LED backlight for top screen' },
        ]
      },
      {
        symptom: 'No Display (Bottom Screen)',
        steps: [
          { text: 'Check bottom LCD power', nets: ['VCC_LCD2', 'LCD2_VCC'], hint: 'Bottom LCD needs 3.3V' },
          { text: 'Verify digitizer', nets: ['TP_VCC'], hint: 'Touch digitizer needs power' },
        ]
      },
    ]
  },

  // ── DELL MOTHERBOARDS ──────────────────────────────────
  dell: {
    name: 'Dell Laptop/Motherboard',
    icon: '💻',
    boards: ['XPS 13', 'XPS 15', 'Latitude 5520', 'Inspiron 15', 'Precision 5560', 'G15 5511', 'Alienware m15'],
    symptoms: [
      {
        symptom: 'No Power',
        steps: [
          { text: 'Check DC jack input', nets: ['DCIN', 'VCC_IN'], hint: 'Should be 19V from Dell adapter' },
          { text: 'Verify 3V/5V ALW', nets: ['VCC_3V_ALW', 'VCC_5V_ALW'], hint: 'Always-on rails from PWM controller' },
          { text: 'Check EC power', nets: ['EC_VCC', 'VCC_EC'], hint: 'Embedded Controller needs standby power' },
          { text: 'Probe power button', nets: ['PWR_BTN', 'PWR_SW'], hint: 'Power button signal to EC' },
          { text: 'Verify PCH power', nets: ['VCC_PCH', 'PP1V05_PCH'], hint: 'PCH standby rail' },
        ]
      },
      {
        symptom: 'No Charging',
        steps: [
          { text: 'Check adapter ID pin', nets: ['ADAPTER_ID', 'PSID'], hint: 'Dell adapter has ID pin for recognition' },
          { text: 'Verify charging IC', nets: ['BQ24780S', 'CHG_IC'], hint: 'Dell uses BQ24780S or similar' },
          { text: 'Check ACOK signal', nets: ['ACOK', 'AC_PRESENT'], hint: 'Adapter present signal' },
        ]
      },
      {
        symptom: 'No Display',
        steps: [
          { text: 'Check GPU voltage', nets: ['VCC_GPU', 'GPU_CORE'], hint: 'GPU core voltage for display' },
          { text: 'Verify eDP panel power', nets: ['VDD_PANEL', 'LCD_VCC'], hint: '3.3V for eDP panel' },
          { text: 'Check backlight', nets: ['BKL_EN', 'BKL_VOUT'], hint: 'Backlight enable and voltage' },
        ]
      },
    ]
  },

  // ── LENOVO MOTHERBOARDS ────────────────────────────────
  lenovo: {
    name: 'Lenovo Laptop/Motherboard',
    icon: '💻',
    boards: ['ThinkPad X1', 'ThinkPad T14', 'IdeaPad 3', 'Legion 5', 'Yoga 9i', 'ThinkPad P15'],
    symptoms: [
      {
        symptom: 'No Power',
        steps: [
          { text: 'Check DC input', nets: ['DCIN', 'VCC_IN'], hint: 'Should be 20V from Lenovo adapter' },
          { text: 'Verify 3V/5V ALW', nets: ['PP3V_ALW', 'PP5V_ALW'], hint: 'Always-on rails' },
          { text: 'Check EC', nets: ['EC_VCC', 'EC_RST'], hint: 'Lenovo uses ITE EC' },
          { text: 'Probe power button', nets: ['PWR_BTN', 'PWR_SW'], hint: 'Power button to EC' },
        ]
      },
      {
        symptom: 'No Charging',
        steps: [
          { text: 'Check adapter detection', nets: ['AC_OK', 'AC_PRESENT'], hint: 'Adapter present signal' },
          { text: 'Verify charging IC', nets: ['CHG_IC', 'BQ24780S'], hint: 'Charging controller' },
          { text: 'Check SMBus to battery', nets: ['SMB_CLK', 'SMB_DAT'], hint: 'Smart battery communication' },
        ]
      },
    ]
  },

  // ── ASUS MOTHERBOARDS ──────────────────────────────────
  asus: {
    name: 'ASUS Laptop/Motherboard',
    icon: '💻',
    boards: ['ROG Strix G15', 'TUF Gaming A15', 'ZenBook 14', 'VivoBook 15', 'ROG Zephyrus G14'],
    symptoms: [
      {
        symptom: 'No Power',
        steps: [
          { text: 'Check DC input', nets: ['DCIN', 'VCC_IN'], hint: 'Should be 19V from ASUS adapter' },
          { text: 'Verify 3V/5V ALW', nets: ['PP3V_ALW', 'PP5V_ALW'], hint: 'Always-on rails' },
          { text: 'Check EC', nets: ['EC_VCC', 'EC_RST'], hint: 'ASUS uses ENE EC' },
          { text: 'Probe power button', nets: ['PWR_BTN', 'PWR_SW'], hint: 'Power button to EC' },
        ]
      },
    ]
  },

  // ── MICROSOFT SURFACE ──────────────────────────────────
  surface: {
    name: 'Microsoft Surface',
    icon: '💻',
    boards: ['Surface Pro 7', 'Surface Pro 8', 'Surface Laptop 4', 'Surface Go 2', 'Surface Book 3'],
    symptoms: [
      {
        symptom: 'No Power',
        steps: [
          { text: 'Check Surface Connect input', nets: ['VCC_IN', 'DCIN'], hint: 'Should be 12V from Surface Connect' },
          { text: 'Verify USB-C PD input', nets: ['VBUS', 'VCC_USB'], hint: 'USB-C PD input for newer models' },
          { text: 'Check PMIC', nets: ['PMIC_VIN', 'VCC_PMIC'], hint: 'Surface uses custom PMIC' },
          { text: 'Probe power button', nets: ['PWR_BTN', 'PWR_SW'], hint: 'Power button to PMIC' },
        ]
      },
      {
        symptom: 'No Display',
        steps: [
          { text: 'Check display power', nets: ['VCC_DISP', 'LCD_VCC'], hint: 'Display needs 3.3V' },
          { text: 'Verify eDP lines', nets: ['EDP_TX', 'MIPI_DSI'], hint: 'eDP or MIPI to display' },
          { text: 'Check backlight', nets: ['BKL_VCC', 'BKL_EN'], hint: 'Backlight for LCD' },
        ]
      },
    ]
  },
};

// ═══════════════════════════════════════════════════════════
// GENERIC FAULT TREES (applies to all manufacturers)
// ═══════════════════════════════════════════════════════════

const GENERIC_FAULT_TREE = [
  {
    symptom: 'Liquid Damage',
    steps: [
      { text: 'Visual inspection for corrosion', nets: [], hint: 'Look for green/white corrosion on board' },
      { text: 'Check for shorted power rails', nets: [], hint: 'Use multimeter in diode mode on all rails' },
      { text: 'Clean with isopropyl alcohol', nets: [], hint: '99% IPA and soft brush for cleaning' },
      { text: 'Check under ICs for trapped moisture', nets: [], hint: 'Use hot air to dry under BGA chips' },
      { text: 'Verify all rails after cleaning', nets: [], hint: 'Re-check all power rails after cleaning' },
    ]
  },
  {
    symptom: 'Overheating / Fan Always On',
    steps: [
      { text: 'Check thermal sensor readings', nets: [], hint: 'Read thermal sensors via BIOS or software' },
      { text: 'Probe CPU/GPU thermal diode', nets: [], hint: 'Open circuit on thermal diode = max fan' },
      { text: 'Check NTC thermistors', nets: [], hint: 'Should measure 5-50kΩ at room temp' },
      { text: 'Verify fan PWM signal', nets: ['FAN_PWM', 'FAN_TACH'], hint: 'PWM duty controls fan speed' },
      { text: 'Inspect for shorted rail', nets: [], hint: 'Use thermal camera or freeze spray' },
    ]
  },
  {
    symptom: 'Kernel Panic / Random Crashes',
    steps: [
      { text: 'Check CPU/GPU VRM ripple', nets: ['PPVCORE_CPU', 'PPVCORE_GPU'], hint: 'Ripple >50mVpp suggests VRM fault' },
      { text: 'Verify RAM voltage', nets: ['VDDQ', 'VPP'], hint: 'Unstable RAM voltage causes panics' },
      { text: 'Check SSD power', nets: ['VCC_SSD', 'PP3V3_SSD'], hint: 'Unstable SSD power causes I/O panics' },
      { text: 'Inspect cold joints', nets: [], hint: 'Thermal camera for intermittent connections' },
    ]
  },
  {
    symptom: 'No Network / Ethernet Dead',
    steps: [
      { text: 'Check Ethernet PHY power', nets: ['VCC_ETH', 'PP3V3_ETH'], hint: 'Ethernet PHY needs 3.3V and 1.0V' },
      { text: 'Verify magnetics continuity', nets: [], hint: 'Check Ethernet magnetics coil' },
      { text: 'Probe RJ45 connector', nets: [], hint: 'Check for bent pins or damage' },
    ]
  },
];

// ═══════════════════════════════════════════════════════════
// AI-POWERED FAULT TREE GENERATION
// ═══════════════════════════════════════════════════════════

/**
 * Generate a fault tree using AI based on manufacturer, board model, and symptoms.
 * This function calls the server's /ai endpoint to get a customized fault tree.
 */
async function generateAIFaultTree(manufacturer, boardModel, symptoms, measurements = []) {
  const systemPrompt = `You are a BoardScope fault tree generator. You create detailed diagnostic decision trees for PCB board repair.

Return ONLY a JSON object with this exact structure:
{
  "symptom": "Primary symptom description",
  "steps": [
    {
      "text": "Step description",
      "nets": ["NET_NAME1", "NET_NAME2"],
      "hint": "Expected values or additional info",
      "expected_value": "3.3V",
      "tool": "multimeter"
    }
  ]
}

Rules:
- Be specific to the manufacturer and board model
- Include exact net names where possible
- Order steps from most likely/easiest to least likely/hardest
- Include expected values for measurements
- Keep steps actionable and concise`;

  const userPrompt = `Generate a fault tree for:
Manufacturer: ${manufacturer || 'Unknown'}
Board Model: ${boardModel || 'Unknown'}
Symptom: ${symptoms || 'No power'}
Current measurements: ${measurements.length ? JSON.stringify(measurements) : 'None yet'}

Return a JSON fault tree object.`;

  try {
    const response = await fetch('/ai', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: null, // Use configured model
        max_tokens: 2000,
        system: systemPrompt,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ]
      })
    });

    const data = await response.json();
    if (data.error) {
      console.error('AI fault tree generation error:', data.error);
      return null;
    }

    const text = data.content?.[0]?.text || '';
    // Parse JSON from response
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      return JSON.parse(jsonMatch[0]);
    }
    return null;
  } catch (error) {
    console.error('Failed to generate AI fault tree:', error);
    return null;
  }
}

// ═══════════════════════════════════════════════════════════
// EXPORT / MODULE INTERFACE
// ═══════════════════════════════════════════════════════════

// Get fault tree by manufacturer key
function getFaultTree(manufacturer) {
  return FAULT_TREES[manufacturer] || null;
}

// Get all available manufacturers
function getManufacturers() {
  return Object.keys(FAULT_TREES).map(key => ({
    key,
    name: FAULT_TREES[key].name,
    icon: FAULT_TREES[key].icon,
    boardCount: FAULT_TREES[key].boards.length
  }));
}

// Get symptoms for a manufacturer
function getSymptoms(manufacturer) {
  const tree = FAULT_TREES[manufacturer];
  return tree ? tree.symptoms : [];
}

// Search across all fault trees
function searchFaultTrees(query) {
  const q = query.toLowerCase();
  const results = [];

  for (const [key, tree] of Object.entries(FAULT_TREES)) {
    for (const symptom of tree.symptoms) {
      const matchesSymptom = symptom.symptom.toLowerCase().includes(q);
      const matchingSteps = symptom.steps.filter(step =>
        step.text.toLowerCase().includes(q) ||
        step.hint.toLowerCase().includes(q) ||
        step.nets.some(n => n.toLowerCase().includes(q))
      );

      if (matchesSymptom || matchingSteps.length > 0) {
        results.push({
          manufacturer: key,
          manufacturerName: tree.name,
          manufacturerIcon: tree.icon,
          symptom: symptom.symptom,
          steps: matchingSteps.length > 0 ? matchingSteps : symptom.steps
        });
      }
    }
  }

  // Also search generic fault trees
  for (const symptom of GENERIC_FAULT_TREE) {
    const matchesSymptom = symptom.symptom.toLowerCase().includes(q);
    const matchingSteps = symptom.steps.filter(step =>
      step.text.toLowerCase().includes(q) ||
      step.hint.toLowerCase().includes(q) ||
      step.nets.some(n => n.toLowerCase().includes(q))
    );

    if (matchesSymptom || matchingSteps.length > 0) {
      results.push({
        manufacturer: 'generic',
        manufacturerName: 'Generic',
        manufacturerIcon: '🔧',
        symptom: symptom.symptom,
        steps: matchingSteps.length > 0 ? matchingSteps : symptom.steps
      });
    }
  }

  return results;
}

// Export for browser and Node.js
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    FAULT_TREES,
    GENERIC_FAULT_TREE,
    getFaultTree,
    getManufacturers,
    getSymptoms,
    searchFaultTrees,
    generateAIFaultTree
  };
} else {
  // Browser global
  window.FaultTree = {
    FAULT_TREES,
    GENERIC_FAULT_TREE,
    getFaultTree,
    getManufacturers,
    getSymptoms,
    searchFaultTrees,
    generateAIFaultTree
  };
}
